Repository elastic/go-ucfg, pull requests merged in 2020-04, with the labels that each got.

#155 Fix Dropped Test Error
  ucfg_test.go
Labels: Team:Services, [zube]: In Review

#158 Remove testify/assert from Validator Tests
  validator_test.go
Labels: Team:Services, [zube]: In Review, in progress

#160 Fix: check if target is valid
  CHANGELOG.md
  cfgtest/unpack.go
  error_test.go
  reify.go
  testdata/error/message/invalid_duration_w_meta.golden
  testdata/error/message/invalid_duration_wo_meta.golden
  testdata/error/message/invalid_regexp_w_meta.golden
  testdata/error/message/invalid_regexp_wo_meta.golden
  validator_test.go
  yaml/yaml_test.go
Labels: Team:Services, [zube]: In Review

#162 Update supported go version in travis file
  .travis.yml
Labels: Team:Services, review

#164 Add test for struct with array defaults initializer
  initializer_test.go
Labels: [zube]: In Review, review

#165 Add NOTICE.txt to repository
  NOTICE.txt
  dev-tools/NOTICE.txt.tmpl
  dev-tools/generate_notice
  go.mod
  go.sum
  tools/tools.go
Labels: Team:Services, [zube]: In Review

#166 Check notice
  .ci/check.sh
  .travis.yml
  NOTICE.txt
  dev-tools/generate_notice
  go.mod
  go.sum
  tools/tools.go
Labels: [zube]: In Progress
